esbuild transpiler transform does not support bigint
```
error during build:
Error: Transform failed with 1 error:
assets/index.7c854793.js:112:21: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
```